site_name: ITMO ICT Web Development Tools
site_description: Documentation for the project

theme:
  name: mkdocs

nav:
  - Главная: index.md
  - API: api.md
  - Data model: data-model.md
  - Run guide: run-guide.md